services:
  - type: web
    name: project
    env: python
    region: frankfurt
    plan: free
    buildCommand: ./render_build.sh
    startCommand: ./render_start.sh
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "project-clah.onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://project-clah.onrender.com"